services:
    - type: web
      name: techstore-api
      env: python
      buildCommand: "pip install -r requirements.txt"
      startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
      envVars:
        - key: STRIPE_SECRET_KEY
          sync: false
        - key: PYTHON_VERSION
          value: 3.11.0
